### ISSUE TITLE
Support Calico GlobalNetworkPolicies with applyOnForward=True

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#10]
See https://docs.projectcalico.org/reference/resources/globalnetworkpolicy and https://docs.projectcalico.org/reference/host-endpoints/forwarded

**Comment by zivn** [comment]
We should also support policies with preDNAT=true and doNotTrack=True

**Comment by zivnevo** [comment]
Maybe for now, allow setting these flags to `True` but issue a warning on analysis being an over-approximation...

**Comment by zivnevo** [comment]
Moved to new repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/42)
