### ISSUE TITLE
avoid generating dot file with syntax error

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#142]
When the config name contains dashes (`-`) for instance, the second line with `digraph <digraph name>` in the dot file is with illegal syntax ("stderr: b"Error: bookinfo-new-5.dot: syntax error in line 2 near '-'\r\n").

**Comment by zivnevo** [comment]
Maybe we should run `graphviz` as part of our tests to check syntax validity. We can install it as part of the workflow:
```
          sudo apt install graphviz
```
