### ISSUE TITLE
Show subgraphs and partial report

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#216]
Provide the user with an option to restrict connectivity maps/reports and concentrate only on a given set of deployments.
The report should only refer to deployments that are in the immediate ingress/egress of the given set.

TBD:
1. How to provide the set of deployments to concentrate on. File? Command-line switch? Scheme field?
2. Do we want to present connections between deployments in given set? between deployments in the immediate ingress/egress?

**Comment by shmfr** [comment]
Added subset support. 3 new switches: label_subset, deployment_subset, namespace_subset. Also configurable from scheme file.
