### ISSUE TITLE
Provide explanation per allowed/denied connection

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#268]
Provide explanation per allowed/denied connection - which policies (and rules within policies) are relevant for determining a specific allowed/denied connection between 2 peers in the cluster (and also which connectivity defaults per layer, if they are relevant).

**Comment by zivnevo** [comment]
Basic explainability was implemented.
The rest moved to a new issue in the NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/56)
