### ISSUE TITLE
Improve connectivity graph 

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#278]
- [ ] For nodes which are not captured by any policy and all connections are allowed to/from them - avoid adding their edges, instead mark them in different color (which would mean their connectivity is not limited to/from any other node?)

**Comment by zivnevo** [comment]
@adisos - in light of the recent work by @haim-kermany, do you think this is still needed?

**Comment by adisos** [comment]
I think we can close this issue  as well.
