### ISSUE TITLE
Calico profiles for HostEndpoints: support projectcalico-default-allow

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#300]
Currently removing support of calico profiles with rules(ingress/egress). For HostEndpoints assuming they have no profiles.
Calico allows changing their default-deny to default-allow by adding the profile projectcalico-default-allow.
Consider supporting this as well.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/59)
