### ISSUE TITLE
issue with helm tests

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#353]
Currently when running `run_al_tests ` on my local env , there are helm tests at `k8s_cmdline_tests.yaml` that require running the command `helm template`, but helm is not installed on my env so the tests run crashes with FileNotFoundError.
Need some mechanism to skip such tests if helm is not installed.

**Comment by shmfr** [comment]
fixed with commit 6365c72 (PR Issue353 #367)
