### ISSUE TITLE
Restyle GraphViz output

### ISSUE THREAD

**Issue by esnible** [IBM/network-config-analyzer#358]
I found it hard to read the GraphViz output, for example [this demo graph](https://github.com/np-guard/NP-Guard-Demo/blob/main/analysis_after_netpols_added/demo-connectivity-2.dot.png).

The node labels are very long.  The part that changes is hard to see.
It is difficult to see namespace boundaries if there is more than one namespace.

Here is an example that wraps the K8s namespace in a GraphViz subgraph, and uses **bold** text for the Deployment name:

[esnible-demo-connectivity-2.dot.txt](https://github.com/IBM/network-config-analyzer/files/10023875/esnible-demo-connectivity-2.dot.txt) (Note that this file should be renamed with _.dot_; extension, Github didn't let me upload except as text).
![esnible-np-guard](https://user-images.githubusercontent.com/3237651/202239748-f1d0d752-7588-4957-8860-52179c79ca26.jpg)

It might also be worthwhile to use GraphViz table-style labels for complex edges, to avoid very wide edge labels.  A simple edge might be `UDP :53` or `:8081`, but a complex edge might be

| TCP (layer 7)        |
| ------------------ |
| paths: `/a{4}(/[\\--9A-Z_a-z]*)?` |
| dst_ports :3000 |
| hosts ooo.y.z      |

(It might also be valuable to include several example .pngs in /docs directory of this repo, or in the Markdown of the _NP-Guard-Demo_ repo.)

**Comment by zivnevo** [comment]
Done. Thanks @haim-kermany
