### ISSUE TITLE
fw-rules improvements

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#47]
- [ ] refine allowed_labels: instead of one set, separate by namespace and 'src' or 'dst' labels.
- [ ] labels grouping: add lookahead -- prioritize representation options by their number of instances, not only by number of covered pods.
- [x] Use complementary sets when shorter. For label-grouping use `key not in {val1, val2}`. For connection set use something like `All but TCP:8080` (need a good heuristic here).

**Comment by zivnevo** [comment]
Moved to new repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/43)
