### ISSUE TITLE
default Istio outbound traffic mode usage

### ISSUE THREAD

**Issue by shireenf-ibm** [IBM/network-config-analyzer#500]
- [ ] consider adding a warning when the default Istio outbound traffic mode (ALLOW_ANY) is used  in the absence of sidecar resources (and it adds connectivity to dns peers for example)
- [ ] Should serviceEntry (dns) peers be excluded from analysis in certain cases? e.g. `kube-system` pods are generally not part of the istio mesh

https://github.com/IBM/network-config-analyzer/pull/476#discussion_r1182315537

https://github.com/IBM/network-config-analyzer/pull/476#discussion_r1182351325

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/87)
