### ISSUE TITLE
Export connectivity map using some standard graph format

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#51]
This should be a variant of `ConnectivityMapQuery` with `self.output_config.outputFormat` set to the required graph format.
Use either [tgf](https://en.wikipedia.org/wiki/Trivial_Graph_Format) or [GraphML](https://en.wikipedia.org/wiki/GraphML) or [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)).
Graphs can then be viewed using [yEd Live website](https://www.yworks.com/yed-live/) or [yEd desktop application](https://www.yworks.com/products/yed).

**Comment by tanyaveksler** [comment]
Done.
