### ISSUE TITLE
Extend support of IstioServiceEntry fields

### ISSUE THREAD

**Issue by shireenf-ibm** [IBM/network-config-analyzer#521]
- We already have an initial support of `Istio ServiceEntry` object (supporting its `hosts` field), which produces the `DNSEntry` peers type. 
The new peer type is used by` Istio Sidecar` policies to fulfill the rules and connections between external hosts `(DNSEntry)` and an internal peers. [merged here - 1st PR](https://github.com/IBM/network-config-analyzer/pull/467)

- The basic support of `ServiceEntry` objects, is working with all queries and there are tests examples. [2nd PR](https://github.com/IBM/network-config-analyzer/pull/476)

so far, DNS entries are exported to all namespaces and the TCP connection type to these hosts is All connections.

In this issue we want to expand the support of `ServiceEntry` as following:

- [ ]  add support of `exportTo` filed  - (3rd PR)
the idea is creating policy elements from the "exported" namespaces to the `DNSEntry` peers 
and adding relevant tests

- [ ] add support of `ports` filed - ( 4th PR)
update the policy elements with the `ServiceEntry's ports` and add relevant tests (plus updating the `TCP` type conns which is All Connections in first PRs to the actual ports )

- [ ]  add "complicated" tests , with multiple service-entries which has common hosts but different exportTo/ ports (- 5th PR)

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/88)
