### ISSUE TITLE
Update EquivalenceQuery expected results according to more refined output in optimized solution

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#523]
See `tests/istio_testcases/example_policies/bookinfo-demo/sidecar_examples/equivalence-with-sidecars-scheme.yaml`:
In the original solution, the difference is as follows:
`src: default/ratings-v1-1, dst: 0.0.0.0-255.255.255.255, description: sidecar-with-selector-allows-any allows all connections while sidecar-with-selector-registery-only does not`
while in the optimized solution the difference is as follows:
`src: default/ratings-v1-1, dst: 0.0.0.0-255.255.255.255, description: sidecar-with-selector-allows-any allows communication using protocol TCP while sidecar-with-selector-registery-only does not.`

The difference is due to the exact calculation (and printing) of the difference in the optimized solution.
Until the expected result is updated (after completely moving to the optimized solution, see https://github.com/IBM/network-config-analyzer/issues/495), expected result of this test is commented out.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/95)
