### ISSUE TITLE
Consider keeping optimized connections copies per policy, in addition to copies per rules

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#542]
Relates to PR  https://github.com/IBM/network-config-analyzer/pull/536
In order to support optimized implementation of `RedundancyQuery`, optimized properties are kept per each rule of policy. Optimized properties per policy are lazily evaluated from rules' properties at the first call of `allowed_connections_optimized`.
However, when changing a query, the domain of `src_peers/dst_peers` is changed, and optimized properties are rebuilt according to the new domain, while keeping copies of the original optimized properties. In this case, per policy properties should be recalculated, according to the updated rules' properties.
Possible optimization: consider keeping copies of per policy properties as well, to avoid their recalculation.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/93)
