### ISSUE TITLE
Create abstract class NetworkPolicyRule to be the base of all policy rule classes

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#543]
Relates to PR https://github.com/IBM/network-config-analyzer/pull/536
Add abstract class `NetworkPolicyRule`, and make every policy rule class to inherit from it.
Add `optimized_props` and `optimized_props_copy` members to `NetworkPolicyRule`.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/92)
