### ISSUE TITLE
Different nodes naming conventions in the output formats may cause confusion when user may want to relay on them as input

### ISSUE THREAD

**Issue by shmfr** [IBM/network-config-analyzer#544]
There may be several places when users need to refer to node names as input (like in the subset or explainability features). 
In those cases, users may intuitively conclude that node names for inputs are the same as those displayed in the output.

1. We may want to align the same nodes naming conventions for all output formats.
2. Meantime, all features that have node names input, should specify the exact format of the node naming expected for that feature.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/83)
