### ISSUE TITLE
ingress policy parser issue

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#549]
Change from error to warning the case in the link below (missing port in the service), and just ignore that service rule in the analysis

https://github.com/IBM/network-config-analyzer/blob/master/nca/Parsers/IngressPolicyYamlParser.py#L97

**Comment by zivnevo** [comment]
Also, see if the message can provide more information. I would expect something like
```
Ingress rule redirects traffic to <service-name>:<port-number>, but port <port-number> is not exposed by <service-name>.
```
