### ISSUE TITLE
ipv6 filter flag follow-ups

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#594]
- [ ] consider warning if filter flag is defined as true, but config has ipv6 referenced ip-blocks, and thus that flag is ignored
- [ ] add tests/examples with referenced ipv6 blocks that affect the output of connectivity map and semantic diff 
- [ ] specifically, revisit the fixes from https://github.com/IBM/network-config-analyzer/pull/577/files , and add a relevant example to demonstrate the effect of the included fix there.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/109)
