### ISSUE TITLE
Wrong handling of the global resourceList in combination with livesim

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#638]
- [ ] When both the global `resourceList` and the livesim missing resource contain the same resource kind (e.g., pods), the resources from the global `resourceList` are ignored.
See example `tests/istio_testcases/example_policies/sidecar_examples_w_onlineboutique/sidecars-and-gateways-test-scheme.yaml`:
when the resource `../online_boutique/new_online_boutique_manifests_istio/all_deployments.yaml` appears only in global `resourceList` (remove it from the network config `resourceList`), then on the livesim run this resource is ignored, resulting in all the pods missing.

- [ ] When none of global `resourceList/podList/namespaceList` exist, there is a (time consuming) attempt to load resources from live cluster, even if there is local `resourceList/podList/namespaceList` in a network config. 
Example - comment out the global `resourceList` in the test above.

**Comment by tanyaveksler** [comment]
Indeed, it looks that the current issue relates to the similar problem as described in Issue https://github.com/IBM/network-config-analyzer/issues/593. 
However, it seems that the current issue specifies the problem in more details.
Also, the second part of the current issue describes an additional problem related to livesim.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/104)
