### ISSUE TITLE
Filter out reporting connectivity to DNS entries whenever Istio layer is not present in configuration

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#645]
Since connectivity to DNS entries is controlled only by the Istio layer, K8s and Calico layers cannot block connectivity to DNS entries (the code was changed accordingly). However, if Istio layer it not present in configuration, DNS entries should not appear in the connectivity output. They should probably be filtered out during generation of connectivity report.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/86)
