### ISSUE TITLE
Extend default resource loading in live cluster to istio resources

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#657]
Currently there are the following possible combinations for handling resources in live cluster:

- `nca -r k8s -r istio` =>  loads both k8s and istio reources
- `nca -r k8s` => loads only k8s resources
- no `-r` given => loads only k8s resources

We should probably change the default assumption that both `k8s` and `istio` resources are handled in live cluster.
What do you think, @zivnevo ?

**Comment by tanyaveksler** [comment]
We decided to remove the default (running without `-r` flag), and to give a warning in this case.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/105)
