### ISSUE TITLE
issues with html output

### ISSUE THREAD

**Issue by haim-kermany** [IBM/network-config-analyzer#662]
- [x] sunset svg format as output (multiply svg files )
- [x] handles errors of the kind: Error: Explainability error: derived item Allow policy for virtual service
- [x] support scheme - need to reset for each scheme? 
- [x] handle issue where text title (right below the graph) is sometimes cut in the middle
- [x] better documentation - instructions how to use the graph (e.g. focus node's graph using double click on nodes..)
- [ ] update readme for both html and explainability
- [ ] check for explainability integraty (see comment from tania)
- [ ] add tests
- [ ] add  explainability  quarey

**Comment by haim-kermany** [comment]
comment from tania:
One question - it seems that there is some redundant information in explanations.
For example, sidecars impact only egress direction, so they should probably appear only in src part of the explanations, but they also appear in the dst part (for example, in connections from frontend to checkoutservice

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/110)
