### ISSUE TITLE
Named_ports warnings are no longer counted in config findings

### ISSUE THREAD

**Issue by tanyaveksler** [IBM/network-config-analyzer#724]
`Named_ports` are now resolved in `ConnectivityProperties::make_conn_props` during building policies. `ConnectivityProperties` do not have access to the policy object. Therefore, all warnings related to `named_ports` resolution are printed but not counted in policy findings.
Currently, changed the expected warnings number in relevant scheme files, to make the tests pass.
Consider the possibility of adding the mechanism of warning counting to `ConnectivityProperties`.

**Comment by zivnevo** [comment]
Moved to NP-Guard repo. See [here](https://github.com/np-guard/network-config-analyzer/issues/91)
