### ISSUE TITLE
tests improvement 

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#93]
- [x] add some performance tests, to compare expected runtime per test, and alert for new run with bad/unexpected performance.
- [x] add some options to run tests per categories (e.g. istio / k8s / calico)
- [ ] Add a list of all tests that failed

**Comment by zivnevo** [comment]
Shireen, this is also something to take a look at.
We can start with just measuring and reporting the time per test and per category.

**Comment by shireenf-ibm** [comment]
>     * [ ]  add some options to run tests per categories (e.g. istio / k8s / calico)

Hi, 
is adding a new --flag to choose the category of tests you want to run will be helpful?

**Comment by adisos** [comment]
> > ```
> > * [ ]  add some options to run tests per categories (e.g. istio / k8s / calico)
> > ```
> 
> Hi, is adding a new --flag to choose the category of tests you want to run will be helpful?

yes, a new flag sounds good.
It may be supported for tests of type 'general' or 'output'.
It's easier to start with 'general'. For the 'output' tests we may need to move the test files into relevant categories dirs.

**Comment by shireenf-ibm** [comment]
>     * [ ]  Add a list of all tests that failed

How to output the list of failing file? into a new output file or to the existing log (stdout) under the summary ?

**Comment by adisos** [comment]
> > ```
> > * [ ]  Add a list of all tests that failed
> > ```
> 
> How to output the list of failing file? into a new output file or to the existing log (stdout) under the summary ?

To the existing log under the summary
